### ISSUE TITLE
Compilation error with CM_CACHE=1 and CM_CT=1

### ISSUE THREAD

**Issue by Septien** [round5/code#2]
Hello, 
I was running some timing tests on your scheme, using the test provided by you. When I compile the code using the following directive:
`make optimized ALG=R5ND_0CPA_2iot STANDALONE=1 TAU=0 TIMING=2000 CM_CT=1   CM_CACHE=1`
I get the following errors:
`src/ringmul_cm.c:38:19: error: subscripted value is not an array, pointer, or vector
        k = idx[i][0]; // positive coefficients
src/ringmul_cm.c:49:19: error: subscripted value is not an array, pointer, or vector
        k = idx[i][1]; // negative coefficients
src/ringmul_cm.c:102:19: error: subscripted value is not an array, pointer, or vector
        k = idx[i][0]; // positive coefficients
src/ringmul_cm.c:113:19: error: subscripted value is not an array, pointer, or vector
        k = idx[i][1]; // negative coefficients`
Are those two options meant to be used together? 
Just letting you know I came across this problem, don't know how relevant it would be.
I am compiling it on a Mac computer, with macOS Catalina version 10.15.2. 
Cheers.

**Comment by oscar-jaca** [comment]
Hello, sorry for the late answer. No, you should make it with no CM option, with CM_CACHE option or with CM_CT option. If you are interested in the iot parameter set and you want to run on a device without cache, then no CM option is a good choice. If you want to run on a PC with support for AVX2 instructions, you should do CM_CT=1 AVX2=1. I will add some additional code to avoid the situation you described.

**Comment by Septien** [comment]
Thanks for the response, I will consider it in the future. Cheers.
